packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@clerk/shared': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@clerk/shared"
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
